- bootstrap/_bootstrap_cmds
- pipeline-steps/bootstrap.yaml
- terraform/aks/05-mis/10-managed-identity.tf
https://tools.hmcts.net/jira/browse/DTSPO-214
Refactored the terraform code for new mi convention
```
[ ] Yes
[X] No
```
> renamed the mi names

- terraform/aks/05-mis/11-acr-managed-identity.tf
Adding AcrPush role to ADO SP
```
[ ] Yes
[x] No
```
> Adding AcrPush role to ADO SP

- kubernetes/charts/fluxcd/helm-operator-values.yaml
> Removing reference to stable repo

- config/terraform/ss/vars/01-network/demo.tfvars
- config/terraform/ss/vars/01-network/dev.tfvars
- config/terraform/ss/vars/01-network/ithc.tfvars
- config/terraform/ss/vars/01-network/prod.tfvars
- config/terraform/ss/vars/01-network/sbox.tfvars
- config/terraform/ss/vars/01-network/stg.tfvars
- config/terraform/ss/vars/01-network/test.tfvars
- terraform/aks/01-network/00-init.tf
- terraform/aks/01-network/11-inputs-default.tf
- terraform/aks/01-network/22-private-dns.tf
There can't be a sandbox and prod private endpoints as VPN can only link to one set
> DTSPO-163 Fix privateendpoint linking

- pipeline-steps/destroy-service.yaml
Update to fix issue with pipeline hanging at destroy stage waiting for variable inputs.
https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=108992&view=logs&j=87bb8d00-0a01-58b5-c8c0-9ce1b84fc8c0&t=d2b01af4-2bad-51d1-8c24-1f51f87c9830
```
[ ] Yes
[x] No
```
> AKS TF Destroy - Missing vars

- config/terraform/ss/vars/01-network/sbox.tfvars
> adding sbox.platform.hmcts.net

- config/terraform/ss/vars/03-aks00/prod.tfvars
- config/terraform/ss/vars/04-aks01/prod.tfvars
> AKS SDS Prod scale up min + man nodes

- bootstrap/_bootstrap_cmds
ts=2021-02-18T09:35:11.22548516Z caller=loop.go:217 component=sync-loop warning="detected external change in sync state; the sync state should not be shared by fluxd instances" state="tag ithc"
> Git label should be unique in flux

- aks-build-infrastructure.iml
- config/terraform/ss/vars/03-aks00/dev.tfvars
- config/terraform/ss/vars/04-aks01/dev.tfvars
> AKS SDS Dev scale up min + max nodes

- config/terraform/ss/vars/01-network/ithc.tfvars
- config/terraform/ss/vars/01-network/sbox.tfvars
- config/terraform/ss/vars/01-network/stg.tfvars
- terraform/aks/01-network/11-inputs-default.tf
- terraform/aks/01-network/20-network.tf
> DTSPO-1644 default + additional routes

- config/terraform/ss/vars/01-network/prod.tfvars
> DTSPO-1674 default + additional routes prod

- config/terraform/ss/vars/03-aks00/sbox.tfvars
- config/terraform/ss/vars/04-aks01/sbox.tfvars
Upgrade Sbox Cluster Version to 1.19.9
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> Upgrade Sbox Cluster Version

- config/terraform/ss/vars/03-aks00/sbox.tfvars
- config/terraform/ss/vars/04-aks01/sbox.tfvars
- terraform/aks/01-network/20-network.tf
- terraform/aks/03-aks00/00-init.tf
- terraform/aks/03-aks00/20-aks.tf
- terraform/aks/04-aks01/20-aks.tf
https://tools.hmcts.net/jira/browse/DTSPO-2168
```
[ ] Yes
[ ] No
```
> DTSPO-2168 Test

- config/terraform/ss/vars/03-aks00/demo.tfvars
- config/terraform/ss/vars/03-aks00/dev.tfvars
- config/terraform/ss/vars/03-aks00/ithc.tfvars
- config/terraform/ss/vars/03-aks00/prod.tfvars
- config/terraform/ss/vars/03-aks00/stg.tfvars
- config/terraform/ss/vars/03-aks00/test.tfvars
- config/terraform/ss/vars/04-aks01/demo.tfvars
- config/terraform/ss/vars/04-aks01/dev.tfvars
- config/terraform/ss/vars/04-aks01/ithc.tfvars
- config/terraform/ss/vars/04-aks01/prod.tfvars
- config/terraform/ss/vars/04-aks01/stg.tfvars
- config/terraform/ss/vars/04-aks01/test.tfvars
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> Upgrade Cluster Version to 1.19.9 For All Environments

- config/terraform/ss/vars/01-network/ithc.tfvars
> Move mi data ithc flows to UKW

- azure-pipelines.yml
- pipeline-steps/deploy-network.yaml
- pipeline-steps/deploy-service.yaml
- pipeline-steps/destroy-service.yaml
- pipeline-steps/genesis.yaml
- pipeline-steps/managed_identity.yaml
> Pipeline Fix

- terraform/aks/00-genesis/01-inputs-required.tf
- terraform/aks/00-genesis/02-inputs-default.tf
- terraform/aks/00-genesis/10-genesis.tf
> Add developers_group to required inputs

- config/terraform/ss/vars/03-aks00/ithc.tfvars
- config/terraform/ss/vars/04-aks01/ithc.tfvars
> Dtspo-2396: ITHC: Upgrade to latest

- config/terraform/ss/vars/03-aks00/ithc.tfvars
- config/terraform/ss/vars/04-aks01/ithc.tfvars
> Dtspo-2396: ITHC: Revert to 1.19.9

- config/terraform/ss/vars/03-aks00/demo.tfvars
- config/terraform/ss/vars/03-aks00/dev.tfvars
- config/terraform/ss/vars/03-aks00/ithc.tfvars
- config/terraform/ss/vars/03-aks00/stg.tfvars
- config/terraform/ss/vars/03-aks00/test.tfvars
- config/terraform/ss/vars/04-aks01/demo.tfvars
- config/terraform/ss/vars/04-aks01/dev.tfvars
- config/terraform/ss/vars/04-aks01/ithc.tfvars
- config/terraform/ss/vars/04-aks01/stg.tfvars
- config/terraform/ss/vars/04-aks01/test.tfvars
> Dtspo-2396:  Upgrade to latest version

- README.md
> Dtspo-2629: HouseKeeping: Updated README.md 

- environments/01-network/ithc.tfvars
> Update mi data routes for uksouth hub

- README.md
- azure-pipelines.yml
- components/00-genesis/01-inputs-required.tf
- components/00-genesis/02-inputs-default.tf
- components/00-genesis/10-genesis.tf
- components/04-aks01/00-init.tf
- components/05-mis/02-inputs-default.tf
- components/05-mis/log-analytics.tf
- pipeline-steps/genesis.yaml
https://tools.hmcts.net/jira/browse/DTSPO-382
Update resource tags for the `genesis` deploy pipeline stage
```
[ ] Yes
[x] No
```
> DTSPO-382: Review and fix untagged resources in shared services genesis

- README.md
https://tools.hmcts.net/jira/browse/DTSPO-382
Updating the list of tags used to tag resources to the ones defined in the tag common module for compliance reasons
```
[ ] Yes
[x] No
```
> DTSPO-382: Review and fix untagged resources in shared services

- components/01-network/11-inputs-default.tf
https://tools.hmcts.net/jira/browse/RMI-1226
Add dns zones
- privatelink.dev.azuresynapse.net
- privatelink.sql.azuresynapse.net
```
[ ] Yes
[ ] No
```
> RMI-1226 add azuresynapse dns zone

- bootstrap/deploy-flux.sh
- Only install kustomize if it doesn't exist
```
[ ] Yes
[x] No
```
> DTSPO-1032 - only install kustomize if it doesn't exist

- bootstrap/deploy-flux.sh
set the variable outside the if statement so its set even if kustomize is installed
> DTSPO-1032 fix bootstrap

- bootstrap/deploy-flux.sh
> DTSPO-1032 - fix bootstrap

- components/aks/aks.tf
- use master branch for aks module
```
[ ] Yes
[ ] No
```
> DTSPO-1032 - set aks module to master branch

- components/aks/aks.tf
https://tools.hmcts.net/jira/browse/DTSPO-2879
Adding resource group to store jenkins disks in
```
[ ] Yes
[ x ] No
```
> DTSPO-2879 - Adding resource group for disks

- environments/01-network/ptl.tfvars
> DTSPO-3555 remove sbox dns zones from ptl config

- components/aks/aks.tf
- components/aks/init.tf
- components/aks/inputs-required.tf
https://tools.hmcts.net/jira/browse/DTSPO-2879
Adding AcrPull role on ACR resource groups to agent pool identities
```
[ ] Yes
[ x ] No
```
> DTSPO-2879 - ACR permissions update

- azure-pipelines.yml
- Removing sbox from pipeline to test moving state around
```
[ ] Yes
[x] No
```
> DTSPO-3555 - remove sbox to test

- azure-pipelines.yml
- Removing most environments from the pipeline to move peering state
```
[ ] Yes
[x] No
```
> DTSPO-3555 - move peering state

- azure-pipelines.yml
> DTSPO-3555 mv peering state

- environments/01-network/dev.tfvars
- environments/01-network/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-3575
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> DTSPO-3575 Add dom1.infra.int private dns zone to dev and prod

- components/aks/aks.tf
- components/aks/inputs-default.tf
- environments/aks/ptl.tfvars
- environments/aks/ptlsbox.tfvars
Update aks environments to support var.ptl_cluster
- Merge when this PR has been merged 
https://github.com/hmcts/aks-module-kubernetes/pull/37/files
```
[ ] Yes
[X] No
```
> Update aks environments to support var.ptl_cluster

- environments/01-network/ptl.tfvars
- DTSPO-2880 - adding additional routes for ptl to dev aks cluster address range
- typo in subnet mask
> DTSPO-2880 - adding additional routes for ptl to dev aks vnet

- environments/01-network/ptlsbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-3990
aat.platform.hmcts.net vnet link for ptlsbox
```
[ ] Yes
[x] No
```
> DTSPO-3990 netbox stg-ptlsbox vnet link

- bootstrap/deploy-flux.sh
- components/00-genesis/10-genesis.tf
https://tools.hmcts.net/jira/browse/DTSPO-4609
```
[ ] Yes
[ ] No
```
> DTSPO-4609 upgrade aad-pod-idenity to   latest version

- components/01-network/11-inputs-default.tf
- components/01-network/21-peering.tf
- components/05-mis/03-interpolated-defaults.tf
- components/aks/aks.tf
- components/aks/inputs-default.tf
- components/aks/inputs-required.tf
- environments/aks/sbox.tfvars
- added a linux node pool
- made the min/max count and vm size configurable per pool
- ran terraform fmt
I went with creating a map variable for each of the node pools, I can move them into individual vars if that's preferred.
```
[ ] Yes
[x] No
```
> DTSPO-4676 system user pools

- components/aks/init.tf
Updating to 2.75 
```
[ ] Yes
[x] No
```
> update azurerm to 2.75

- azure-pipelines.yml
- Run pipeline against sbox by default
```
[ ] Yes
[x] No
```
> Build SBOX by default

- bootstrap/deploy-flux.sh
https://tools.hmcts.net/jira/browse/DTSPO-4609
```
[ ] Yes
[ x] No
```
> DTSPO-4609 Upgrade aad pod id to latest version

- bootstrap/deploy-flux.sh
DTSPO-4609 
```
[ ] Yes
[ ] No
```
> DTSPO-4609 Upgrade aad pod id to latest ver

- components/aks/aks.tf
- components/aks/init.tf
- Bug with the ossku being set incorrectly for windows nodes has been fixed in 2.77
```
[ ] Yes
[x] No
```
> Update azureRM tf provider to latest version

- components/aks/aks.tf
- components/aks/inputs-required.tf
- environments/aks/dev.tfvars
> Node pool max pods

- bootstrap/deploy-flux.sh
- Initial update to the deploy_flux script to deploy flux v2 to ptl and sbox
```
[ ] Yes
[x] No
```
> DTSPO-5581 - enable flux v2 deployment for ptl and sbox

- bootstrap/deploy-flux.sh
> Amend deploy-flux.sh

- bootstrap/deploy-flux.sh
> Add kustomize install step for Flux v2

- bootstrap/deploy-flux.sh
> Add workaround for Flux v2 script

- environments/aks/sbox.tfvars
- Patch AKS version sbox to 1.22.4
> Patch AKS version sbox to 1.22.4

- components/00-genesis/01-inputs-required.tf
- components/00-genesis/02-inputs-default.tf
- components/00-genesis/10-genesis.tf
- environments/00-genesis/demo.tfvars
- environments/00-genesis/sbox.tfvars
- pipeline-steps/genesis.yaml
Wasn't 100% sure which way to go but I've added tfvars files for each environment and updated the pipeline. I will also revert the branch and remove the sbox public IPs once it's approved.
```
[ ] Yes
[x] No
```
> DTSPO-6478 - test public ip creation in sbox

- components/00-genesis/10-genesis.tf
- environments/00-genesis/sbox.tfvars
- merged by accident
```
[ ] Yes
[x] No
```
> Switch to master

- components/05-mis/10-managed-identity.tf
- We might want to fine tune this, but to get this ticket a bit further I have just scoped it to the resource group.
```
[ ] Yes
[x] No
```
> DTSPO-6478 - fix permissions so aks can create loadbalancer with pip

- components/00-genesis/01-inputs-required.tf
- components/00-genesis/02-inputs-default.tf
- components/00-genesis/10-genesis.tf
- components/05-mis/10-managed-identity.tf
- environments/00-genesis/demo.tfvars
> DTSPO-6478 - remove public ip support from genesis

- components/01-network/11-inputs-default.tf
N/A
Link the redis and signalr private dns zones with SDS vNets
```
[ ] Yes
[X] No
```
> added link to redis and signalr zones

- azure-pipelines.yml
- components/aks/init.tf
update target cmd for dev_to_stg and added additional envs for this to be applied
```
[ ] Yes
[X] No
```
> update target cmd for dev_to_stg and added additional envs for this to be applied

- kubernetes/rbac/default-rbac.yaml
> Add flux v2 helmrelease permissions

- components/05-mis/10-managed-identity.tf
- added permissions for external dns demo zones to read/write to zones
```
[ ] Yes
[x] No
```
> DTSPO-6498 - add permissions for external dns demo zones

- components/01-network/11-inputs-default.tf
This name was changed, needs to be reflected here. It's breaking my build currently.
https://github.com/hmcts/azure-private-dns/commit/b485f015810e8e817d47009097b86b15f12b346f
```
[ ] Yes
[x] No
```
> Private DNS zone name change

- environments/aks/dev.tfvars
> bump max autoscaling numbers

- environments/01-network/demo.tfvars
- environments/01-network/dev.tfvars
- environments/01-network/ithc.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/ptl.tfvars
- environments/01-network/ptlsbox.tfvars
- environments/01-network/sbox.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
NOTE:
I'm not clear if I've chosen suitable address_prefixes. I simply took the previous address_prefix and incremented the last non-zero item.
> RST-4286 Add subnets for redis

- components/01-network/11-inputs-default.tf
add servicebus dns zone to aks network
```
[ ] Yes
[x] No
```
> DTSPO-6371 - add servicebus dns zone to aks network

- environments/01-network/demo.tfvars
- environments/01-network/dev.tfvars
- environments/01-network/ithc.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
add apim subnets for dev and stg
```
[ ] Yes
[X] No
```
> add apim subnets for dev and stg

- environments/01-network/sbox.tfvars
Creating new subnet for private endpoints in sbox
```
[ ] Yes
[x] No
```
> DTSPO-6371 - create private-endpoint subnet

- environments/aks/demo.tfvars
- environments/aks/dev.tfvars
- environments/aks/ithc.tfvars
- environments/aks/prod.tfvars
- environments/aks/ptl.tfvars
- environments/aks/ptlsbox.tfvars
- environments/aks/sbox.tfvars
- environments/aks/stg.tfvars
- environments/aks/test.tfvars
Was scaling prod cluster and it got deleted, existing cluster can't be re-deployed as not available any more
> Update AKS to latest version

- environments/01-network/demo.tfvars
- environments/01-network/dev.tfvars
- environments/01-network/ithc.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/sbox.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
Description: Adding additional subnets for private endpoints
> DTSPO-6371 - add additional subnets for private endpoints

- environments/01-network/demo.tfvars
- environments/01-network/dev.tfvars
- environments/01-network/ithc.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/sbox.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
Previous cidr ranges weren't valid. Updated to fix.
```
[ ] Yes
[x] No
```
> DTSPO-6371 fix private endpoint subnets

- azure-pipelines.yml
Removing sbox from pipeline until I've finished testing upgrading terraform and azurerm provider in #159 and https://github.com/hmcts/aks-module-kubernetes/pull/48
```
[ ] Yes
[x] No
```
> DTSPO-7029 - remove sbox from main pipeline

- azure-pipelines.yml
- components/01-network/00-init.tf
- components/aks/aks.tf
- components/aks/init.tf
- Upgraded terraform to 1.1.7
- Upgraded azurerm provider to 3.0.2
- Formatted pipeline file
Apply in sbox was fine, no unexpected results: [ADO run](https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=220252&view=logs&j=9529ead6-39ae-5319-1740-9d2035106bd6&t=89b2e481-5d95-5be1-d64b-e101e3d88784)
```
[ ] Yes
[x] No
```
> DTSPO-7029 - upgrade tf and fmt

- azure-pipelines.yml
- Removing sbox from pipeline whilst I move some state around
```
[ ] Yes
[x] No
```
> DTSPO-7029 - remove sbox in prep for state move

- azure-pipelines.yml
Removing ITHC, DEV, DEMO  so I can run the state move
```
[ ] Yes
[x] No
```
> DTSPO-7029 - removing ITHC, DEV, DEMO for state move

- azure-pipelines.yml
- Last few environments being removed from the pipeline for #163
```
[ ] Yes
[x] No
```
> DTSPO-7029 - remove STG, PTL and Prod from pipeline 

- azure-pipelines.yml
- Removing destroy stage from pipeline 
- Fixing targeting to work for sets 
```
[ ] Yes
[x] No
```
> DTSPO-7029 - update cluster targeting in pipeline

- azure-pipelines.yml
Forgot to remove destroy from the list of parameters
```
[ ] Yes
[x] No
```
> DTSPO-7029 - removing destroy from params

- components/aks/aks.tf
- components/aks/inputs-required.tf
- environments/aks/demo.tfvars
- environments/aks/dev.tfvars
- environments/aks/ithc.tfvars
- environments/aks/prod.tfvars
- environments/aks/ptl.tfvars
- environments/aks/ptlsbox.tfvars
- environments/aks/sbox.tfvars
- environments/aks/stg.tfvars
- environments/aks/test.tfvars
This change will accommodate cluster upgrades being managed via code.
```
[ ] Yes
[x] No
```
> DTSPO-7029 - manage cluster upgrades as code

- environments/aks/dev.tfvars
Testing deleting dev cluster 00 
```
[ ] Yes
[x] No
```
> DTSPO-7029 - testing - delete dev 00

- environments/aks/dev.tfvars
Adding dev 00 back in 
```
[ ] Yes
[x] No
```
> DTSPO-7029 - add dev-00 back in

- components/aks/aks.tf
> Revert aks module back to master

- azure-pipelines.yml
https://tools.hmcts.net/jira/browse/DTSPO-7031
Temporarily removing envs so work on branch "DTSPO-7031" doesn't get overwritten.
```
[ ] Yes
[x] No
```
> DTSPO-7031 Temporarily remove envs so work on branch doesn't get overwritten

- components/05-mis/00-init.tf
- components/05-mis/02-inputs-default.tf
https://tools.hmcts.net/jira/browse/DTSPO-7031
```
[ ] Yes
[x] No
```
> DTSPO-7031 Hardcode subscriptions

- azure-pipelines.yml
- components/05-mis/00-init.tf
- components/05-mis/02-inputs-default.tf
- components/05-mis/acr-permissions.tf
https://tools.hmcts.net/jira/browse/DTSPO-7031
So we can run all envs now that change has taken place.
```
[ ] Yes
[x] No
```
> DTSPO-7031 Uncomment environments from pipeline

- environments/01-network/prod.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-8385
Added libragob-postgresql subnets.
```
[ ] Yes
[X] No
```
> Added libragob-postgresql subnets.

- bootstrap/register-cluster-with-dynatrace.sh
*
Update register-cluster-with-dynatrace.sh to add Curl retries
```
[ ] Yes
[X] No
```
> Update register-cluster-with-dynatrace.sh to add Curl retries

- bootstrap/deploy-flux.sh
Enable fluxv2 on test
```
[ ] Yes
[x] No
```
> DTSPO-6488 - Enable fluxv2 on test

- environments/aks/test.tfvars
Destroy test-01 cluster
Will be rebuilt afterwards with flux v2 only
```
[ ] Yes
[x] No
```
> DTSPO-6488 - Destroy test-01 cluster

- environments/aks/test.tfvars
JIRA link (if applicable)
Change description
Re-add cluster 00 in test
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> DTSPO-6488 - Re-add test-01 cluster

- environments/aks/test.tfvars
Remove test-00 cluster
Will be rebuilt with fluxv2 only
```
[ ] Yes
[x] No
```
> DTSPO-6488 - Destroy test-00 cluster

- environments/aks/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6490
```
[ ] Yes
[x] No
```
> DTSPO-6488 Destroy stg00

- environments/aks/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6490
Bring back 00, take down 01.
```
[ ] Yes
[x] No
```
> DTSPO-6488 Destroy stg01

- environments/aks/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6490
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> DTSPO-6490 Bring back stg01

- environments/aks/test.tfvars
Re-add test-00 cluster
```
[ ] Yes
[x] No
```
> DTSPO-6488 - Re-add test-00 cluster

- environments/01-network/demo.tfvars
Reverting change made to app gw subnet
```
[ ] Yes
[x] No
```
> Reverting change made to app gw cidr block

- environments/aks/demo.tfvars
Deleting demo-01 cluster 
```
[ ] Yes
[x] No
```
> Remove demo 01 cluster

- pipeline-steps/deploy-network.yaml
- pipeline-steps/deploy-service.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9048
Add publishPlanResults to terraform pipeline
```
[ ] Yes
[x] No
```
> DTSPO-9048 - Add publishPlanResults

- bootstrap/deploy-flux.sh
DTSPO-6494 
Remove Flux V1 from Prod Clusters
```
[ ] Yes
[X] No
```
> DTSPO-6494 - Remove Flux V1 from Prod Clusters

- bootstrap/deploy-flux.sh
Enable flux v2 on ptlsbox
```
[ ] Yes
[x] No
```
> DTSPO-6493 - Deploy flux v2 to ptl sbox

- components/aks/aks.tf
- components/aks/inputs-default.tf
- environments/aks/prod.tfvars
- environments/aks/stg.tfvars
disable containerInsights except for stg/prod
```
[ ] Yes
[X] No
```
> disable containerInsights except for stg/prod

- bootstrap/deploy-flux.sh
Removing ability to deploy flux v1 to ptlsbox as all apps have been migrated to flux v2
```
[ ] Yes
[x] No
```
> DTSPO-6493 - remove ptlsbox from flux v1 list

- environments/aks/sbox.tfvars
Redeploying sbox-01 now its been destroyed 
```
[ ] Yes
[x] No
```
> DTSPO-6492 - re-deploy sbox 01

- components/aks/aks.tf
- environments/aks/sbox.tfvars
Testing the csi driver add-on on the sbox 01
```
[ ] Yes
[x] No
```
> DTSPO-9539 - deploy csi driver add-on to sbox 01

- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-8697
Removing sbox-00 cluster temporarily as it is in a failed state
Will re-add after destroying
```
[ ] Yes
[x] No
```
> DTSPO-8697 - Remove sbox-00

- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-8697
Re-add sbox-00
```
[ ] Yes
[x] No
```
> DTSPO-8697 - Re-add sbox-00

- environments/aks/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-9517
Re-add ithc-01 cluster
```
[ ] Yes
[x] No
```
> DTSPO-9517 - Re-add ithc-01 cluster

- environments/aks/dev.tfvars
We should only run one cluster in dev and  01 is deployed so removing 00
```
[ ] Yes
[x] No
```
> Remove dev 00

- environments/aks/prod.tfvars
Allow deployment of csi driver to prod
```
[ ] Yes
[x] No
```
> DTSPO-9539 - allow deployment of csi driver add-on to prod

- environments/aks/dev.tfvars
> Sds preview max

- azure-pipelines.yml
- components/aks/init.tf
These two combinations work, using both latest versions seems to break things.
```
[ ] Yes
[x] No
```
> DTSPO-10279 - upgrade terraform and azurerm provider

- environments/aks/dev.tfvars
Enable automatic patch updates for the dev environment
```
[ ] Yes
[x] No
```
> DTSPO-10279 - enable automatic patch updates for dev

- components/01-network/22-private-dns.tf
- environments/aks/demo.tfvars
- environments/aks/dev.tfvars
- environments/aks/ithc.tfvars
- environments/aks/ptlsbox.tfvars
- environments/aks/stg.tfvars
- environments/aks/test.tfvars
- Enabled automatic updates for all other non-prod environments
- Ran `terraform fmt`
```
[ ] Yes
[x] No
```
> DTSPO-10279 - enable automatic patch updates for non prod envs

- environments/01-network/test.tfvars
N/A
Added perf test resolution for SDS Test
```
[ ] Yes
[x] No
```
> Added perftest for SDS test

- .github/workflows/updatecli.yaml
- updatecli/values.github-action.yaml
- updatecli/weekly.d/aks-version.yaml
https://tools.hmcts.net/jira/browse/DTSPO-10277
Use updatecli to automatically update the major AKS version. 
```
[ ] Yes
[x] No
```
> DTSPO-10277 Updatecli

- .github/workflows/updatecli.yaml
- updatecli/updatecli.d/aks-version.yaml
- updatecli/values.github-action.yaml
https://tools.hmcts.net/jira/browse/DTSPO-10277
Re-introduce updatecli 
```
[ ] Yes
[x] No
```
> DTSPO-10277 - Re-introduce updatecli

- .github/workflows/updatecli.yaml
- updatecli/get-latest-aks-upgrade-version.sh
- updatecli/updatecli.d/aks-version.yaml
- updatecli/values.github-action.yaml
> Test upgrade aks version updatecli loops

- updatecli/get-latest-aks-upgrade-version.sh
> Test jq method of retrieving aks versions

- environments/01-network/dev.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
VIH-9422 - Update Routes for AppGw
VIH-9422 - Update Routes for AppGw
```
[ ] Yes
[ x ] No
```
> VIH-9422 - Update Routes for AppGw

- azure-pipelines.yml
https://tools.hmcts.net/jira/browse/DTSPO-9696
Add a new variable to azure pipeline file to ensure apply is not skipped.
```
[ ] Yes
[x] No
```
> added new variable in pipelines file

- azure-pipelines.yml
Re-introduce self hosted ADO pool to avoid timeouts
```
[ ] Yes
[x] No
```
> move aks actions to self hosted ado agentpool

- updatecli/get-latest-aks-upgrade-version.sh
- updatecli/updatecli.d/aks-version.yaml
- updatecli/values.github-action.yaml
Remove the need to change the dev and demo config when clusters are swapped over
Copying over work done in https://github.com/hmcts/aks-cft-deploy/pull/313
```
[ ] Yes
[ ] No
```
> Remove the need to change the dev and demo config 

- environments/aks/stg.tfvars
Disable AKS containerInsights STG
```
[ ] Yes
[X] No
```
> Disable AKS containerInsights STG

- environments/01-network/ptl.tfvars
> updated Routes to allow postgresql

- components/aks/aks.tf
[DTSPO-11424](https://tools.hmcts.net/jira/browse/DTSPO-11424)
Add AKS Auto Shutdown Service Principal
```
[ ] Yes
[X] No
```
> DTSPO-11424: Add AKS Auto Shutdown Service Principal

- environments/aks/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-11430
Add autoShutdown tag for AKS SDS test cluster
```
[ ] Yes
[X] No
```
> DTSPO-11430 - Add autoShutdown tag for AKS SDS test cluster

- environments/aks/demo.tfvars
Demo 01 is already built and tested from a different flux branch and a different branch in aks-sds-deploy. Moving this change into master as first step in cluster switchover, to re-bootstrap demo01 and then begin the swap
Change has gone into master successfully to switch to name overrides https://github.com/hmcts/sds-flux-config 
```
[ ] Yes
[ ] No
```
> Rebuild 01

- environments/aks/demo.tfvars
Backend in appgw has been swapped and demo 01 is built. There is a small issue with dns but this was the same since Nov.
```
[ ] Yes
[ ] No
```
> Remove demo 00 cluster

- environments/aks/ithc.tfvars
- environments/aks/ptlsbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-11430
Enable Auto-Shutdown for PTLSBOX and ITHC
```
[ ] Yes
[X] No
```
> DTSPO-11430 - Enable Auto-Shutdown for PTLSBOX and ITHC

- environments/aks/sbox.tfvars
Increasing pods slightly for sbox to fix issue with nmi pod issue
```
[ ] Yes
[x] No
```
> Increase max pods to 40 for sbox linux nodes

- environments/aks/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-11430
Add Auto-Shutdown to Demo
```
[ ] Yes
[X] No
```
> DTSPO-11430 - Add Auto-Shutdown to Demo

- environments/aks/demo.tfvars
> Enable demo 00

- components/05-mis/10-managed-identity.tf
> Add external dns perms for preview and remove for demo

- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-12090
Update sbox-01 to 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12090 - Update sbox-01 to 1.25

- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-12090
Updae sbox-00 cluster to k8s 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12090 - Update sbox-00 to 1.25

- environments/aks/ithc.tfvars
Update ithc-01 to 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12091 - Update ithc-01 to 1.25

- environments/aks/ithc.tfvars
Upgrade ithc-00 to 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12091 - Update ithc-00 to 1.25

- components/00-genesis/99-outputs.tf
- components/aks/aks.tf
- components/aks/disk.tf
- components/aks/interpolated-defaults.tf
see https://github.com/hmcts/aks-module-kubernetes/pull/87
> Migrate disk RG to deploy repo

- environments/aks/test.tfvars
Update test-01 to kubernetes 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12091 - Update test-01 to 1.25

- environments/aks/stg.tfvars
Upgrade stg-01 to kubernetes 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12091 - Update stg-01 to 1.25

- environments/aks/stg.tfvars
Upgrade stg-00 to kubernetes 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12091 - Update stg-00 to 1.25

- environments/aks/test.tfvars
Upgrade test-00 to kubernetes 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12091 - Update test-00 to 1.25

- environments/aks/demo.tfvars
Upgrade demo-00 to kubernetes 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12091 - Update demo-00 to 1.25

- environments/aks/dev.tfvars
Upgrade dev-01 to kubernetes 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12091 - Update dev-01 to 1.25

- environments/aks/ptlsbox.tfvars
Upgrade ptlsbox-00 to kubernetes 1.25
```
[ ] Yes
[x] No
```
> DTSPO-12091 - Update ptlsbox-00 to 1.25

- environments/01-network/demo.tfvars
VIH-0000 - Update Demo AppGw Routes
```
[ ] Yes
[ x ] No
```
> VIH-0000 - Update Demo AppGw Routes

- .github/workflows/run-updatecli.yaml
- components/aks/aks.tf
- updatecli/get-deprecation.sh
https://tools.hmcts.net/jira/browse/DTSPO-12641
Adding Pluto run in GitHub Action and supporting script
```
[ ] Yes
[x] No
```
> Adding Pluto run and supporting script

- components/01-network/21-peering.tf
https://tools.hmcts.net/jira/browse/DTSPO-12697
Updating sbox to use vnet peering module
[ ] Yes
[x] No
```
> Dtspo 12697 vnet peering

- updatecli/updatecli.d/aks-version.yaml
Output the cluster name to make things clearer when the pipeline fails
```
[ ] Yes
[x] No
```
> Troubleshooting - output the cluster name to make things a bit clearer

- updatecli/get-latest-aks-upgrade-version.sh
- updatecli/updatecli.d/aks-version.yaml
Staging is in a failed state and that seems to have broken the pipeline. As a first step I'm just going to get the script to check both clusters if the first fails
```
[ ] Yes
[x] No
```
> Try both clusters if first one fails

- components/01-network/21-peering.tf
https://tools.hmcts.net/jira/browse/DTSPO-12697
update prod peering
```
[ ] Yes
[x ] No
```
> update prod vnet peering

- components/01-network/21-peering.tf
Updates VPN peering to new module
```
[ ] Yes
[x] No
```
> Updates VPN peering to new module

- .github/workflows/pluto.yaml
- .github/workflows/run-updatecli.yaml
- updatecli/updatecli.d/aks-version.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13769
Applying pluto enhancement 
```
[ ] Yes
[x] No
```
> Updating pluto run in github action

- environments/aks/sbox.tfvars
DTSPO-12895
Upgrade cluster 00 to 1.26 version
```
[ ] Yes
[ x ] No
```
> Upgrade Sbox 00 version

- environments/aks/sbox.tfvars
DTSPO-12895
Upgrade sbox 01 to 1.26 version
```
[ ] Yes
[ x ] No
```
> Sbox upgrade

- components/01-network/21-peering.tf
Adds moved blocks for peering modules
```
[ ] Yes
[x] No
```
> Adds moved blocks for peering modules

- components/01-network/10-inputs-required.tf
- components/01-network/20-network.tf
- environments/01-network/demo.tfvars
- environments/01-network/dev.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
* Align repo with aks-module-network changes found in [this PR](https://github.com/hmcts/aks-module-network/pull/33)
```
[ ] Yes
[x] No
```
> Align repo with changes to aks-module-network

- environments/01-network/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14134
```
[ ] Yes
[x] No
```
> feat: added route for jumpbox nonprod

- environments/aks/ithc.tfvars
* Upgrade ithc01 aks to 1.26
```
[ ] Yes
[x] No
```
> Upgrade ithc01 aks to 1.26

- environments/aks/ithc.tfvars
* Upgrade ITHC00 AKS version to 1.26
```
[ ] Yes
[x] No
```
> Upgrade ITHC-00 AKS version to 1.26

- environments/01-network/dev.tfvars
- environments/01-network/ptl.tfvars
- environments/01-network/test.tfvars
https://tools.hmcts.net/jira/browse/HMIS-1206
Adding routes for HMI
```
[ ] Yes
[x] No
```
> HMIS-1206 - Fixing HMI to VH connection in Dev and Test

- environments/01-network/ptl.tfvars
- environments/01-network/ptlsbox.tfvars
> Add new subnet in ptl and ptlsbox

- environments/aks/test.tfvars
* Upgrade ss-test-01 to 1.26 AKS version
```
[ ] Yes
[x] No
```
> Upgrade ss-test-01 to 1.26 AKS version

- environments/aks/test.tfvars
* Upgrade sds-test-00 to 1.26 AKS version
```
[ ] Yes
[x] No
```
> Upgrade sds-test-00 to 1.26 AKS version

- environments/aks/stg.tfvars
* Upgrade ss-stg-01 to 1.26 AKS version
```
[ ] Yes
[x] No
```
> Upgrade ss-stg-01 to 1.26 AKS version

- environments/aks/ptlsbox.tfvars
DTSPO-12896
Upgrade Ptlsbox to 1.26
```
[ ] Yes
[ x ] No
```
> upgrade ptlsbox to 1.26

- components/01-network/11-inputs-default.tf
- components/01-network/21-peering.tf
https://tools.hmcts.net/jira/browse/DTSPO-14427
Remove ukw-hub-sbox-int
```
[ ] Yes
[X] No
```
> Remove ukw-hub-sbox-int

- components/01-network/21-peering.tf
Change back to orig but change for_each logic for peering in sbox
```
[ ] Yes
[X] No
```
> Change back to orig but change for_each logic

- environments/01-network/test.tfvars
Add UDR for vh test env
```
[ ] Yes
[X] No
```
> Update UDR for vh-perf-test-test

- environments/01-network/ptlsbox.tfvars
DTSPO-12896
Private endpoints using wrong subnet address
```
[ ] Yes
[ x ] No
```
> update subnet for private endpoints

- environments/aks/ptl.tfvars
PTL has been upgraded via az portal and reflecting this as code
```
[ ] Yes
[ ] No
```
> Upgrade PTL post-upgrade

- environments/aks/prod.tfvars
DTSPO-12897
Prod 00 has been upgraded to 1.26
```
[ ] Yes
[ ] No
```
> Reflect prod00 upgrade in code

- environments/aks/prod.tfvars
Prod 01 has been upgraded now, so reflecting this in code
```
[ ] Yes
[ ] No
```
> Reflect 01 upgrade in code

- environments/aks/test.tfvars
enable oms agent on test for containerInsights
```
[ ] Yes
[X] No
```
> enable oms agent on test for containerInsights

- environments/01-network/ptl.tfvars
Update lower pre vnets to flow via nonprod Palo
```
[ ] Yes
[X] No
```
> Update lower pre vnets to flow via nonprod Palo

- azure-pipelines.yml
- components/01-network/11-inputs-default.tf
- components/01-network/20-network.tf
https://tools.hmcts.net/jira/browse/DTSPO-14613
Cleanup UKWEST refs in repos
```
[ ] Yes
[x] No
```
> DTSPO-14613: Cleanup UKWEST refs in repos

- environments/aks/dev.tfvars
- environments/aks/ptl.tfvars
- environments/aks/stg.tfvars
[DTSPO-13971](https://tools.hmcts.net/jira/browse/DTSPO-13971)
Enable auto-shutdown via tag for dev, staging and ptl environments
```
[ ] Yes
[X] No
```
> DTSPO-13971 - Enable auto-shutdown via tag for dev, staging and ptl environments (DO NOT MERGE)

- components/aks/aks.tf
- components/aks/inputs-default.tf
- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14034
Test arm based linux nodes on sbox
```
[ ] Yes
[x] No
```
> DTSPO-14034 - Use arm linux nodes in sbox

- azure-pipelines.yml
> updating keyvault to use service principle

- bootstrap/deploy-flux.sh
> Move to new patches

- bootstrap/deploy-flux.sh
- components/aks/aks.tf
- components/aks/inputs-default.tf
- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-13635
Same as CNP - added ASO to the bootstrap
```
[ ] Yes
[X ] No
```
> added ASO to bootstrap

- bootstrap/deploy-flux.sh
> fixed incorrect variable name

- components/aks/aks.tf
- components/aks/inputs-default.tf
Removed flags as its applied at module level.
```
[ ] Yes
[X ] No
```
> removed flags as its applied at module level

- environments/aks/dev.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15273
Adding in dev-00 to upgrade dev env to 1.27
> Adds in dev-00 to be built

- environments/aks/dev.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14192
Update 01 version and comment out 00
> Update 01 version and comment out 00

- environments/aks/test.tfvars
[DTSPO-15362](https://tools.hmcts.net/jira/browse/DTSPO-15362)
Upgrading ss-test-00 version to 1.27
> testenv-cluster-upgrade

- environments/aks/test.tfvars
[DTSPO-15362](https://tools.hmcts.net/jira/browse/DTSPO-15362)
Upgrading cluster version to 1.27
> Dtspo 15362 cluster upgrade

- environments/aks/demo.tfvars
[DTSPO-15377](https://tools.hmcts.net/jira/browse/DTSPO-15377)
Updating code to match cluster version after upgrade 1.27
> version-upgrade

- environments/aks/demo.tfvars
[DTSPO-15377](https://tools.hmcts.net/jira/browse/DTSPO-15377)
Updating version 1.27
> cluster version upgrade

- environments/aks/ptlsbox.tfvars
[DTSPO-15382](https://tools.hmcts.net/jira/browse/DTSPO-15382)
Updating code to match cluster version upgrade 1.27
> cluster-upgrade

- environments/aks/stg.tfvars
[DTSPO-14192](https://tools.hmcts.net/jira/browse/DTSPO-14192)
Updating code to match cluster version 1.27
> Dtspo 14192 cluster upg

- components/aks/aks.tf
[DTSPO-15290](https://tools.hmcts.net/jira/browse/DTSPO-15290)
adding additional nodepool for cronjobs
> DTSPO-15290 Create node pool for cronjobs

- environments/aks/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15360
upgrade ithc cluster 00 to v1.27
> upgrade ithc cluster 00 to v1.27

- components/aks/aks.tf
[DTSPO-15290](https://tools.hmcts.net/jira/browse/DTSPO-15290)
Adding cron-job node pool
> DTSPO-15290 adding cronjob node pool

- environments/aks/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15360
Upgrading ithc 01 cluster to v1.27
> upgrading ithc 01 to v1.27

- environments/aks/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14193
Update cluster to new and latest version
> DTSPO-14193: Update cluster to new and latest version

- components/05-mis/10-managed-identity.tf
* Change aks-dev-mi role assignement to subscription level in STG
> DEV: change aks-dev-mi role assignement to subscription level in STG

- components/05-mis/10-managed-identity.tf
Accidentally changed this during a naming change
> Update admin-mi ID

- components/05-mis/10-managed-identity.tf
Use principal_id... not client_id
> Update principal_id reference to correct value

- environments/aks/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14193
Updating k8s version
> DTSPO-14193: Updating k8s version

- environments/aks/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14193
Update k8s version for 01
> DTSPO-14193: Update k8s version for 01

- components/00-genesis/00-init.tf
- components/01-network/00-init.tf
- components/05-mis/00-init.tf
- components/07-network-rg/00-init.tf
- components/aks/init.tf
[DTSPO-8700](https://tools.hmcts.net/jira/browse/DTSPO-8700)
Merge master into DTSPO-8700 branch to update terraform to v3.78.0
> Update Terraform azurerm to v3.78.0 (#381)

- components/aks/aks.tf
- components/aks/inputs-default.tf
- environments/aks/sbox.tfvars
- to be used in auto start up scripts
> Add startup mode for sbox clusters

- components/aks/aks.tf
- components/aks/inputs-default.tf
- environments/aks/prod.tfvars
See https://github.com/hmcts/aks-cft-deploy/pull/571
> Disable AKS diagnostics in nonprod

- components/01-network/10-inputs-required.tf
- components/01-network/20-network.tf
- environments/01-network/demo.tfvars
- environments/01-network/dev.tfvars
- environments/01-network/ithc.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/ptl.tfvars
- environments/01-network/ptlsbox.tfvars
- environments/01-network/sbox.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
add prod,stg,test postgres-expanded subnet
> add prod,stg,test postgres-expanded subnet

- environments/aks/ithc.tfvars
Seems unnecessary to run these all the time.
> Drop to one cluster on ITHC

- environments/01-network/ptl.tfvars
N/A
Added route for data catalogue dev vnet to the nonprod hub.
> feat: added route for dc dev net to nonprod hub

- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15840
Updating Kubernetes Version from 1.27 to 1.28 for cluster 00
> DTSPO-15840: Updating Kubernetes Version

- environments/aks/sbox.tfvars
> DTSPO-15840: Updating k8s version to latest

- environments/aks/ptlsbox.tfvars
Updating k8s version to latest from 1.27 to 1.28.
> DTSPO-15841: Updating k8s version to latest

- environments/aks/ithc.tfvars
Updating k8s version to current from 1.27 to 1.28
> DTSPO-15841: Updating k8s version to current

- environments/01-network/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16239
dc-purview-dev was given a new IP range and this change is to update the routes.
> Update dc_vnet_dev IP address range

- environments/aks/demo.tfvars
Update the K8s version from 1.27 to 1.28
> DTSPO-15841: Update the K8s version

- environments/aks/demo.tfvars
Update k8s version on demo 01 from 1.27 to 1.28
> DTSPO-15841: Update k8s version on demo 01

- environments/01-network/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16357
Add route to dc_vnet_test (10.11.75.32/27) to route table aks-ptl-route-table
> Add dc_vnet_test to route table

- environments/aks/test.tfvars
Update k8s version to latest from 1.27 to 1.28
> DTSPO-15841: Update k8s version to latest

- environments/aks/stg.tfvars
Update k8s to latest from 1.27 to 1.28
> DTSPO-15841: Update k8s to latest

- environments/aks/stg.tfvars
Update k8s for stg01 from 1.27 to 1.28
> DTSPO-15841: Update k8s for stg 01

- environments/aks/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15842
Update k8s for PTL from 1.27 to 1.28
> DTSPO-15842: Update k8s for PTL

- environments/aks/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15842
Update k8s version for Prod-01 from 1.27 to 1.28
> DTSPO-15842: Update k8s version for Prod-01

- pipeline-steps/bootstrap.yaml
DTSPO-15819
Skip setting Issuer URL when Cluster is set to All
> Dtspo 15819

- azure-pipelines.yml
Setting param "runManualStart" to true so that the AKS manual start step is triggered.
> Setting aks manual start to true

- components/aks/aks.tf
https://tools.hmcts.net/jira/browse/DTSPO-14865
added node_os_channel_upgrade to enable when env is sbox
> DTSPO-14865-replace-kured

- environments/01-network/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17101
Update prod appgw routes to add Libra prod in IH.
> feat: add IH route to specific Palo

- components/aks/aks.tf
- components/aks/inputs-default.tf
- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14865
Added maintenance window config obj
> DTSPO-14865-replace-kured-v2

- environments/01-network/demo.tfvars
> additional subnet for az lb

- components/aks/aks.tf
- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16590
update sbox to 1.29
> DTSPO-16590 - Update sbox.tfvars

- environments/aks/ptlsbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16590
Upgraded plsbox
> DTSPO-16590 - upgrade ptlsbox

- environments/aks/dev.tfvars
Upgrade Dev environment to 1.29.2
> DTSPO-16591 - upgrade DEV

- environments/aks/ithc.tfvars
> DTSPO-16591 - upgrading ITHC

- environments/aks/demo.tfvars
> DTSPO-16591 - demo upgrade

- environments/aks/test.tfvars
> DTSPO-16591 - upgrade test clusters

- environments/aks/stg.tfvars
> DTSPO-16591 - upgrade stg

- environments/aks/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16592
Upgrading SDS PTL cluster
> DTSPO-16592 - upgrading sds ptl cluster

- environments/aks/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16592
Updated prod clusters
> DTSPO-16592 - upgrading sds prod cluster

- azure-pipelines.yml
> add new pool

- environments/01-network/stg.tfvars
> add in azure lb subnet for staging

- environments/01-network/ptl.tfvars
> Adding BAIS non-prod VNET to peerings

- environments/01-network/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17768 & https://tools.hmcts.net/jira/browse/DTSPO-17695
> feat: added routes to pin Hendon traffic to Palo vm0

- environments/01-network/demo.tfvars
- environments/01-network/dev.tfvars
- environments/01-network/ithc.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17794
> feat: added routes to pin IH traffic to single Palo

- environments/01-network/demo.tfvars
N/A
Correct 102PF and Hendon routes.
> fix: correct Hendon demo route

- components/aks/aks.tf
- components/aks/inputs-default.tf
- environments/aks/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18000
- Removes arm node pool that is currently deployed to sbox
> Dtspo 18000 remove arm aks nodes

- environments/01-network/ithc.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/test.tfvars
> add in additional lb subnets

- environments/01-network/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18158
Expand ITHC route to include the whole vnet address space, not just IaaS.
> fix: expand ITHC route

- components/aks/aks.tf
- environments/aks/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18090
- enable node os image upgrades ithc
> DTSPO-18090: ITHC - enable node os image upgrades

- components/aks/aks.tf
- environments/aks/demo.tfvars
- environments/aks/dev.tfvars
- environments/aks/ptlsbox.tfvars
- environments/aks/stg.tfvars
- environments/aks/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18090
- enable node os image upgrades for
> DTSPO-18090: enable node os image upgrades non-prod

- components/aks/aks.tf
- environments/aks/prod.tfvars
- environments/aks/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18086
- enable node os updates in ptl & prod
> DTSPO-18086: Prod: enable node os updates in ptl & prod

- environments/01-network/demo.tfvars
- environments/01-network/dev.tfvars
- environments/01-network/ithc.tfvars
- environments/01-network/prod.tfvars
- environments/01-network/stg.tfvars
- environments/01-network/test.tfvars
N/A
Added routes for the JBox address space to enable testing/access from Jumpboxes.
> feat: added AppGw Routes for JBox access

- environments/aks/stg.tfvars
> Staging monitoring enabled

- components/01-network/11-inputs-default.tf
- environments/01-network/dev.tfvars
- environments/01-network/stg.tfvars
update dev stg route from prod to nonprod hub
- dev should not route to prod hub
- changes will switch routing from prod hub to non prod hub between dev<->stg aks vnets
> Hub network update devstg

- environments/01-network/stg.tfvars
Update stg.tfvars for ss-dev to ss-stg appgw route to nonprod
> Update stg.tfvars for ss-dev to ss-stg appgw route to nonprod

- environments/01-network/dev.tfvars
- environments/01-network/stg.tfvars
- update dev to stg routes for egress snat 
- Manually applied to routes to test, works from ss-dev -> ss-aks-appgw
```
/ # telnet 10.148.32.138 80
Connected to 10.148.32.138
```
> update dev to stg routes for egress snat

- environments/aks/stg.tfvars
See [DTSPO-18781](https://tools.hmcts.net/jira/browse/DTSPO-18781))
Up max number of nodes - Stg and Prod now matching
> update max nodes on stg (match prod)

- environments/01-network/dev.tfvars
Required as ss-dev speaks to pre-stg
> Required as ss-dev speaks to pre-stg

- environments/aks/sbox.tfvars
> Upgrade 00 to 1.30

- environments/aks/sbox.tfvars
> Upgrade 01 to 1.30

- environments/aks/ptlsbox.tfvars
> Upgrade SDS PTLSBOX to 1.30

- environments/01-network/demo.tfvars
Reverting changes to interface to restore service in `demo` environment
> Revert changes for egress interface

- environments/aks/demo.tfvars
> Upgrade 00 demo

- environments/01-network/demo.tfvars
Reverting route table entries back
> Reverting routes back to single nic

- environments/aks/demo.tfvars
> Upgrade 01 demo

- components/00-genesis/00-init.tf
- components/01-network/00-init.tf
- components/05-mis/00-init.tf
- components/07-network-rg/00-init.tf
- components/aks/init.tf
- environments/aks/test.tfvars
Backfill aks upgrade to code after successful aks 1.3 upgrade
All pods running and healthy
> Test 00 AKS upgrade

- environments/aks/test.tfvars
Upgrade went through successfully, backfilling to code
> Update test 01 to latest AKS

- environments/aks/stg.tfvars
Upgrade went successfully, backfilling to code
> Update stg 00 to latest AKS version

- environments/aks/stg.tfvars
Upgrade has been successful, backfilling this to code
> Upgrade stg01 to latest AKS version

- environments/aks/ptl.tfvars
After successful upgrade, backfilling this to code
> Update ss ptl to latest AKS version

- environments/aks/prod.tfvars
Upgrade ran successfully, backfilling this to code
> Backfill ss prod 00 upgrade to code

- environments/aks/prod.tfvars
Upgrade successful, so backfilling this to code
> Upgrade prod-01 to latest

- components/00-genesis/00-init.tf
- environments/01-network/dev.tfvars
temporary setting as NAT still in place
> temporary setting as NAT still in place

- environments/01-network/ptl.tfvars
See [DTSPO-19332](https://tools.hmcts.net/jira/browse/DTSPO-19332)
Add a route so PTL Jenkins can connect to Darts Modernisation dev postgres server
> DTSPO-19332 - Add darts-modernisation routes

- components/aks/aks.tf
[DTSPO-19027](https://tools.hmcts.net/jira/browse/DTSPO-19027)
adding additional settings to automatic cluster due to failing on pipeline
> DTSPO-19027 Updating settings on automatic cluster

- components/aks/aks.tf
- environments/aks/sbox.tfvars
[DTSPO-19027](https://tools.hmcts.net/jira/browse/DTSPO-19027))
updating settings for the auto cluster deployment as it is failing on the pipeline.
> DTSPO-19027-updating-auto-cluster-settings

- components/aks/aks.tf
N/A
Adding an interval to fix an error in the pipeline:
```
│   "message": "ImageCleaner intervalHours 0 is out of range [24 - 2160], please correct it.",
```
> Add image cleaner interval

- components/aks/aks.tf
N/A
`interval_hours` has been changed to camelCase `intervalHours`
> Fix image cleaner interval to camelCase

- components/aks/aks.tf
N/A
Az_api resource is having issues applying due to concurrent writes on the managed identity.
The resource wants to add `removing_special_chars`
The module is replacing this resource with the `azurerm_federated_identity_credential` in sbox initially to confirm this doesn't cause issues
> Switch to azurerm_federated_identity_credential in sbox

- azure-pipelines.yml
https://tools.hmcts.net/jira/browse/DTSPO-22074
Correct the name of the Azure pipepline to say it its either plan ot apply when runs automatically.
> DTSPO-22074 - Fix the name issue on the pipeline

- environments/01-network/demo-pinned-aks-routes.yaml
- environments/01-network/demo-pinned-appgw-routes.yaml
https://tools.hmcts.net/jira/browse/DTSPO-22443
Testing failover for PALO-VM-0 to PALO-VM-01 in Demo as part of DTSPO-22443
N/A
> DTSPO-22443 - Testing palo failover in demo

- environments/aks/stg.tfvars
> Scale staging cluster

- environments/aks/stg.tfvars
- environments/aks/test.tfvars
Looks to have been accidentally added here - https://github.com/hmcts/aks-sds-deploy/pull/658 
Currently costing approx - £8.3k per year
> disable aks logging on test and stg

- environments/aks/test.tfvars
temporary enabling oms_agent_enabled in ss-test
- requested by Nickin (perftest team)
> temporary enabling oms_agent_enabled in ss-test

- environments/01-network/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25519
Adding routes to heritage nle vnet address spaces/
> DTSPO-25519 Add routes to heritage nle vnet

- environments/aks/ptlsbox.tfvars
- environments/aks/sbox.tfvars
Update AKS versions in code after upgrade
> Update AKS versions in code after upgrade

- environments/aks/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25673
Upgrade ITHC cluster to 1.32
> DTSPO-25673 Upgrade SDS cluster to 1.32

- environments/aks/demo.tfvars
- environments/aks/dev.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25673
Upgrade dev and demo clusters to 1.32
> DTSPO-25673 Upgraded dev and demo clusters to 1.32

- environments/aks/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25685
Upgrade completed for SDS test clusters to 1.32
> DTSPO-25685 Upgraded test clusters to 1.32

- environments/aks/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25685
Upgraded sds stg 00 cluster to 1.32
> DTSPO-25685 upgraded stg 00 cluster to 1.32

- environments/01-network/prod-pinned-aks-routes.yaml
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> fix: 10.1.97.0/32 -> 10.1.97.0/24

- environments/aks/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25677
Upgraded ss-prod-00-aks to k8s 1.32
> DTSPO-25677 Upgraded ss-prod-00-aks to 1.32

- azure-pipelines.yml
https://tools.hmcts.net/jira/browse/DTSPO-24241
Uncomment PTl and PROD stages
Rollout to Non-prod was successful
I rolled out Toffee and Jenkins-webhook changes in non-prod, secrets were created successfully, controller threw no errors and looked like it could pull from those gitrepos without any problems.
Below some outputs which should prove this for each SDS cluster
<details>
<summary>ss-sbox-00-aks</summary>
```bash
Switched to context "ss-sbox-00-aks".
Checking Cluster: ss-sbox-00-aks
-- New Flux GitHub App Secret: --
NAME                     TYPE     DATA   AGE
github-app-credentials   Opaque   3      3h14m
-- Flux pod status: --
NAME                                 READY   STATUS    RESTARTS   AGE
source-controller-6cd558bc58-hkc9g   1/1     Running   0          21h
-- New Flux …
```
> Uncomment PTL and Production stages to create new GitHub App secret during bootstrapping in PTL and PROD

- environments/aks/test.tfvars
Revert from dtspo-26412
Revert now perftesting is done 
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> revert test container insights

- environments/01-network/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-27826
- Update stg routes post-cloud gateway STG NAT changes
- repoint to .37
> DTSPO-27826: Update stg routes post-cloud gateway STG NAT changes
