hmcts/aks-sds-deploy

config/terraform/ss/vars/01-network/demo.tfvars, config/terraform/ss/vars/01-network/dev.tfvars, config/terraform/ss/vars/01-network/ithc.tfvars, config/terraform/ss/vars/01-network/prod.tfvars, config/terraform/ss/vars/01-network/sbox.tfvars, config/terraform/ss/vars/01-network/stg.tfvars, config/terraform/ss/vars/01-network/test.tfvars
To support private endpoint DNS in use by the MI Data Platform, vnet links for the below private dns zones added for all environments:
-   privatelink.database.windows.net
-   privatelink.blob.core.windows.net
-   privatelink.vaultcore.azure.net
-   privatelink.datafactory.azure.net
-   privatelink.postgres.database.azure.com
```
[ ] Yes
[x] No
```
=> Added vnet links to central private dns zones

bootstrap/_bootstrap_cmds
DTSPO-261 - update --git-path so that the common-overlay directory is picked up by flux
https://tools.hmcts.net/jira/browse/DTSPO-161
updating --git-path list so that flux picks up the new common-overlays directory
```
[ ] Yes
[x] No
```
=> DTSPO-261 - update --git-path for flux

components/aks/aks.tf
https://tools.hmcts.net/jira/browse/DTSPO-2879
Pipeline currently failing as data resource inside module is ran before resource group is created
```
[ ] Yes
[ x ] No
```
=> DTSPO-2879 - Adding depends_on in kubernetes module

components/aks/aks.tf
We've had to swap over the node pools as the system node pool isn't allowed to be the default.
```
[ ] Yes
[x] No
```
=> DTSPO-4676 - set linux np as default

bootstrap/deploy-flux.sh
https://tools.hmcts.net/jira/browse/DTSPO-5953
Update bootstrap script to only install Flux v1 for non-migrated envs
```
[ ] Yes
[x] No
```
=> Only install Flux v1 for non-migrated envs

azure-pipelines.yml
Adding resource group as a target reference also. 
- If attempting to deploy just 01, it will attempt to deploy kubernetes_resource_group00/01 without target
- Tested on cft-aks
- Updated so it can reference
`azurerm_resource_group.kubernetes_resource_group[1]: `
```
[ ] Yes
[X] No
```
=> Add additional target for aks component

environments/aks/dev.tfvars
To get around this:
`│ Error: creating Managed Kubernetes Cluster "ss-dev-01-aks" (Resource Group "ss-dev-01-rg"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="AgentPoolK8sVersionNotSupported" Message="Version 1.21.2 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check [https://aka.ms/supported-version-list"](https://aka.ms/supported-version-list%22)`
```
[ ] Yes
[x] No
```
=> Patch AKS version dev to 1.22.4

components/05-mis/10-managed-identity.tf
- Added minimal permissions for external dns. 
- went down the local & for_each route so it's easy to configure another environment that uses external dns (preview potentially) if needed.
```
[ ] Yes
[x] No
```
=> DTSPO-6498 external dns permissions as code

bootstrap/deploy-flux.sh, environments/aks/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6917
Upgrade Kubernetes version to 1.22.4 and enable Flux v2 for Staging clusters
```
[ ] Yes
[x] No
```
=> DTSPO-6917 Upgrade Kubernetes version to 1.22.4 and enable Flux v2 for Staging clusters

environments/01-network/demo.tfvars, environments/01-network/dev.tfvars, environments/01-network/ithc.tfvars, environments/01-network/prod.tfvars, environments/01-network/sbox.tfvars, environments/01-network/stg.tfvars, environments/01-network/test.tfvars
Fixing the private endpoint subnets, /22 needs to start on x.x.x.0, otherwise it is incorrect.
```
[ ] Yes
[x] No
```
=> DTSPO-6371 - fix private endpoint subnets

bootstrap/deploy-flux.sh
https://tools.hmcts.net/jira/browse/DTSPO-6489
Enable flux v2 on ithc environment via deploy-flux.sh
```
[ ] Yes
[x] No
```
=> DTSPO-6489 - enable fluxv2 on ithc

environments/aks/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-9517
Remove ithc-01 cluster
Will be re-added in subsequent PR
Testing that managed identity is being used to authenticate to azure container registry
```
[ ] Yes
[x] No
```
=> DTSPO-9517 - Remove ithc-01 cluster

components/aks/aks.tf, environments/aks/prod.tfvars, environments/aks/sbox.tfvars
- Set csi driver add-on to be deployed by default 
- Don't enable in prod
- Clean up sbox
```
[ ] Yes
[x] No
```
=> DTSPO-9539 - set csi driver add-on to be deployed

environments/aks/sbox.tfvars
Removing the patch from the kubernetes_cluster_version var for sbox to enable automatic updates
```
[ ] Yes
[x] No
```
=> DTSPO-10279 - enable automatic updates for sbox

.github/workflows/updatecli.yaml, updatecli/weekly.d/aks-version.yaml
https://tools.hmcts.net/jira/browse/DTSPO-10771
Revert updatecli to use single configuration template and loop over environments instead.
Issue raised on updatecli github to address the issues with targets/pull requests.
Tracked originally under [DTSPO-10747](https://tools.hmcts.net/jira/browse/DTSPO-10747) 
```
[ ] Yes
[x] No
```
=> Revert updatecli config to single template

components/00-genesis/00-init.tf, components/01-network/00-init.tf, components/05-mis/00-init.tf, components/07-network-rg/00-init.tf, components/aks/init.tf, environments/aks/sbox.tfvars, modules/vnet_peering/init.tf
https://tools.hmcts.net/jira/browse/DTSPO-10551
Upgrade SBOX Cluster to 1.23
(Code changed from 1.24 -> 1.23 as can only bump one version at a time. Clusters currently on version 1.22)
```
[ ] Yes
[X] No
```
=> DTSPO-10551 - Upgrade SBOX Cluster to 1.23

updatecli/get-latest-aks-upgrade-version.sh
This fixes `ERROR: ✗ validation error: transformer input is empty` breaking the pipeline, when there's only preview upgrades available.
Example of:
```json
{
"agentPoolProfiles": null,
"controlPlaneProfile": {
"kubernetesVersion": "1.24.6",
"name": null,
"osType": "Linux",
"upgrades": [
{
"isPreview": true,
"kubernetesVersion": "1.25.2"
}
]
},
"id": "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourcegroups/ss-sbox-00-rg/providers/Microsoft.ContainerService/managedClusters/ss-sbox-00-aks/upgradeprofiles/default",
"name": "default",
"resourceGroup": "ss-sbox-00-rg",
"type": "Microsoft.ContainerService/managedClusters/upgradeprofiles"
}
```
```
[ ] Yes
[x] No
```
=> Return current kubernetes version when no non-preview upgrades available

azure-pipelines.yml
Switch to running AKS stage on self hosted agent pool to overcome maximum job timeouts https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts 
This should help with AKS GA upgrades which usually take longer than currently allowed 60 minutes imposed by MS Hosted Agentpool
```
[ ] Yes
[x] No
```
=> Move AKS clusters stage to hmcts-cftptl-agent-pool self hosted pool

azure-pipelines.yml
Add 180 mintues explicit timeout to DeployInfrastructure job to prevent timeouts
```
[ ] Yes
[x] No
```
=> Add 180 mintues explicit timeout to DeployInfrastructure job

environments/01-network/ptl.tfvars
Currently failing with 
`subnets/private-endpoints has an invalid CIDR notation. For the given prefix length, the address prefix should be 10.147.96.0/22`
Next available /22 is `10.147.100.0/22` - do we even need this size for private endpoints?
```
[ ] Yes
[X] No
```
=> correct private endpoints subnet

azure-pipelines.yml, pipeline-steps/bootstrap.yaml, scripts/update-issuer-url.sh
[Similar done in CFT](https://github.com/hmcts/aks-cft-deploy/pull/537)
https://tools.hmcts.net/jira/browse/DTSPO-15096
This change:
- Adds functionality for automatically updating the OIDC Issuer URL in flux during the aks-sds-deploy pipeline, which is necessary when a cluster is rebuilt, due to workload identity work
- Bootstrapping clusters is now dependent on this step having run (even if it produces no changes)
=> DTSPO-15096 Add auto-update issuer URL

components/05-mis/10-managed-identity.tf
Gives the new admin-mi access to acme for traefik migration to workload identity.
Adding it this way instead of for_each, saves recreation of existing role assignment and makes cleaning things up later on easier
=> Give admin mi acme access

components/05-mis/10-managed-identity.tf
These were removed on the assumption they were not needed as only set in two envs, but since it has been failing because of the removal
=> Add missing role assignments back

components/05-mis/10-managed-identity.tf
[DTSPO-12677](https://tools.hmcts.net/jira/browse/DTSPO-12677)
ASO is configured with STG subscription - so can't override to use dev-mi in admin namespace in dev env. Instead access must be given for the stg mi, which has a federated credential for the dev service account to read from this key vault.
=> DTSPO-12677 Add stg-mi access to dev acme vault

environments/aks/dev.tfvars
Updating k8s version to current on DEV from 1.27 to 1.28
=> DTSPO-15841: Updating k8s version to current on DEV

environments/aks/test.tfvars
Update k8s on test00 cluster from 1.27 to 1.28
=> DTSPO-15841: Update k8s on test00 cluster

environments/01-network/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16913
=> fix: temporarily route DNAT AKS traffic to VM0

environments/aks/prod.tfvars
N/A
Bump the max nodes in the linux pool from 10 (the default) to 12.
=> feat: bump max nodes in prod from 10 to 12

environments/aks/prod.tfvars
N/A
Update sku tier for AKS clusters in prod, currently set to standard but but pipeline tries to set them back to free.
=> fix: update tier in prod

environments/01-network/demo.tfvars, environments/01-network/dev.tfvars, environments/01-network/ithc.tfvars, environments/01-network/prod.tfvars, environments/01-network/stg.tfvars, environments/01-network/test.tfvars
Dynatrace routes were missing on nonprod aks route tables
Connections from dynatrace activegates were reaching applications on the clusters but could not make their way back
This will fix alerts and errors occurring in nonprod dynatrace
=> Add missing routes to dynatrace

environments/01-network/ptl.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18174
Expand sds test route to the whole subnet rather than just IaaS
=> fix: expand ss test aks route to include the whole vnet

components/01-network/21-peering.tf
update stg peering name for nonprod hub
Current error - 
`│ Error: A resource with the ID "/subscriptions/74dacd4f-a248-45bb-a2f0-af700dc4cf68/resourceGroups/ss-stg-network-rg/providers/Microsoft.Network/virtualNetworks/ss-stg-vnet/virtualNetworkPeerings/hubUkS" already exists `
=> update stg peering name for nonprod hub

environments/01-network/stg.tfvars
See https://tools.hmcts.net/jira/browse/DTSPO-18814
In order to get the traffic flowing correctly from BAIS to PDDA, we needed to add this route to the aks-stg-rout-table. Since then, we can see the correct traffic on the Palo. [https://portal.azure.com/#@HMCTS.NET/resource/subscriptions/74dacd4f-a248-45bb-a2f0-a[…]s/Microsoft.Network/routeTables/aks-stg-route-table/overview](https://portal.azure.com/#@HMCTS.NET/resource/subscriptions/74dacd4f-a248-45bb-a2f0-af700dc4cf68/resourceGroups/ss-stg-network-rg/providers/Microsoft.Network/routeTables/aks-stg-route-table/overview)
Change manually applied and confirmed as working
=> Adding bau-bais to the nle network

environments/01-network/demo.tfvars
Currently working through the DARTS persistence session issues in `demo` environment, made some changes, manually, to the route table entries to point back to the `lb` frontend private ip, subsequent pipeline runs reverted them.
Adding configuration changes to code for the duration of this period and may be reverted back if there is the need too.
=> Updated changes to persisits during testing

environments/01-network/dev.tfvars, environments/01-network/stg.tfvars
cleanup as ss-dev does not use NAT addresses now if internal HMCTS Azure
=> cleanup as ss-dev does not use NAT addresses now if internal HMCTS Azure

environments/01-network/dev.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-19071
- `ss-dev` -> `ss-stg` found to be very intermittent whilst investigating the above ticket.
- Fix went in on Friday but have been asked to remove route `ss-stg-vnet` as part of this work, so that all `ss-dev` -> `ss-stg` traffic is sent to 10.11.72.36
=> Remove ss-stg-vnet route

environments/aks/stg.tfvars
VH team are having difficulty scaling pods in stg `  0/19 nodes are available:` 
Have been working with them to reduce pod count, requests for mem and cpu etc but still this error shows when trying to add a pod as stg is full but can not scale any more.
=> Increase stg nodepool scaling limit

environments/aks/ithc.tfvars
This is part of a spike to increase AKS node efficiency, we are currently underutilising our nodes, and other tests we've carried out seem to point to scheduling on nodes having problems due to only allowing 30 pods per node, causing upward autoscaling 
We don't use Azure CNI Overlay, so each node requests an IP in your subnet, and each node then has an IP range it can assign to pods
This POC is to see how AKS behaves when we increase this, see ticket to see PDF of explanation for all envs in CFT/SDS
Hoping to learn:
- What terraform wants
- Does default LeastAllocated scheduling strategy still force us onto more nodes even when we increase this?
- How the current spread of pods handles this change with no manual intervention
- If this does lead to a reduced node count
Ithc-00:
subnet: …
=> DTSPO-19113: Increase max pods per node

environments/01-network/dev.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-19164
Adding a routing rule to enable traffic flow from dev environment to interim hosting. This was previously covered using using the same route table as prod but with a recent change dev has its own route table but was missing this route.
Tested manually by adding the route via the Azure portal.
=> Adding a routing rule to enable traffic flow from dev environment to interim hosting

environments/aks/test.tfvars
See [VIH-11053](https://tools.hmcts.net/jira/browse/VIH-11053)
VH app Helm upgrades are failing because there is not enough CPU capacity across the max 10 nodes on ss-test-00/01-aks clusters to allow the replica set to schedule the new pods. Increasing the max node count to 16 matches that set on staging.
=> VIH-11053 increase test aks linux node pool max limit to 16

components/aks/aks.tf
Reverts hmcts/aks-sds-deploy#651
Using the dedicated fed cred resource requires the managed identity be deleted.
A local apply seemed to work with the `removing_special_chars` value
=> Revert "Switch to azurerm_federated_identity_credential in sbox"

environments/01-network/ptl.tfvars
Need to access mi_vnet_dev resources from SDS Jenkins pipelines.
PTL to the mi_vnet_stg resource seems to work OK so assuming its an issue with the next hop from PTL to dev.
=> Added PTL to mi_vnet_dev route

environments/01-network/demo-pinned-aks-routes.yaml, environments/01-network/demo-pinned-appgw-routes.yaml
Reverts hmcts/aks-sds-deploy#662
Failing back over to VM-0 following a successful test as part of DTSPO-22443
=> Revert "DTSPO-22443 - Testing palo failover in demo"

components/05-mis/10-managed-identity.tf
https://tools.hmcts.net/jira/browse/DTSPO-24310
- Giving dev and demo managed identity contributor access to the genesis-rg resource group.
- This is needed as the MI needs write access to the resource group for flux-system workload identity.
=> DTSPO-24310: Giving dev and demo MI contributor access to genesis-rg

azure-pipelines.yml
https://tools.hmcts.net/jira/browse/DTSPO-24310
- Uncommenting Prod in azure-pipelines to enable staging through the testing of the new bootstrapping, which has been edited to use workload identity for flux system.
- PTL and prod were commented out in https://github.com/hmcts/aks-sds-deploy/pull/676.
- Bootstrapping has already been applied to the lower environments and PTL successfully.
- The bootstrapping has been applied to and tested successfully on the non-prod environments [here](https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=792299&view=results).
- It was added to PTL in [this PR](https://github.com/hmcts/aks-sds-deploy/pull/677) and applied in [this run](https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=793351&view=results).
=> DTSPO-24310: Uncommenting prod in azure-pipelines to add back to pipeline steps
